name: Build Static Qt LTS
on: [push]

jobs:
  build-static-Qt:
    name: build static Qt
    runs-on: windows-2022

    steps:
      - name: Install vs2019 toolset
        shell: pwsh
        run: |
          echo "Download vs_enterprise.exe for VS2019 (version 16)"
              Invoke-WebRequest -Uri "https://aka.ms/vs/16/release/vs_enterprise.exe" -OutFile "vs_enterprise.exe" -UseBasicParsing

              echo "Install VS2019 with required components"

              $process = Start-Process -FilePath "./vs_enterprise.exe" -ArgumentList @(
                  "install",
                  "--installPath", "C:\VS2019",
                  "--add", "Component.Dotfuscator",
                  "--add", "Component.Linux.CMake",
                  "--add", "Component.UnityEngine.x64",
                  "--add", "Component.Unreal.Android",
                  "--add", "Microsoft.Component.Azure.DataLake.Tools",
                  "--add", "Microsoft.Component.PythonTools.Miniconda",
                  "--add", "Microsoft.Component.PythonTools.Web",
                  "--add", "Microsoft.Component.VC.Runtime.UCRTSDK",
                  "--add", "Microsoft.Net.ComponentGroup.4.6.2.DeveloperTools",
                  "--add", "Microsoft.Net.ComponentGroup.4.7.1.DeveloperTools",
                  "--add", "Microsoft.Net.Component.4.7.2.SDK",
                  "--add", "Microsoft.Net.Component.4.7.2.TargetingPack",
                  "--add", "Microsoft.Net.ComponentGroup.4.7.DeveloperTools",
                  "--add", "Microsoft.VisualStudio.Component.AspNet45",
                  "--add", "Microsoft.VisualStudio.Component.Azure.Kubernetes.Tools",
                  "--add", "Microsoft.VisualStudio.Component.Azure.ServiceFabric.Tools",
                  "--add", "Microsoft.VisualStudio.Component.Debugger.JustInTime",
                  "--add", "Microsoft.VisualStudio.Component.DslTools",
                  "--add", "Microsoft.VisualStudio.Component.EntityFramework",
                  "--add", "Microsoft.VisualStudio.Component.FSharp.Desktop",
                  "--add", "Microsoft.VisualStudio.Component.LinqToSql",
                  "--add", "Microsoft.VisualStudio.Component.SQL.SSDT",
                  "--add", "Microsoft.VisualStudio.Component.Sharepoint.Tools",
                  "--add", "Microsoft.VisualStudio.Component.PortableLibrary",
                  "--add", "Microsoft.VisualStudio.Component.TeamOffice",
                  "--add", "Microsoft.VisualStudio.Component.TestTools.CodedUITest",
                  "--add", "Microsoft.VisualStudio.Component.TestTools.WebLoadTest",
                  "--add", "Microsoft.VisualStudio.Component.UWP.VC.ARM64",
                  "--add", "Microsoft.VisualStudio.Component.VC.140",
                  "--add", "Microsoft.VisualStudio.Component.VC.ATL.ARM",
                  "--add", "Microsoft.VisualStudio.Component.VC.ATLMFC",
                  "--add", "Microsoft.VisualStudio.Component.VC.ATLMFC.Spectre",
                  "--add", "Microsoft.VisualStudio.Component.VC.CLI.Support",
                  "--add", "Microsoft.VisualStudio.Component.VC.CMake.Project",
                  "--add", "Microsoft.VisualStudio.Component.VC.DiagnosticTools",
                  "--add", "Microsoft.VisualStudio.Component.VC.Llvm.ClangToolset",
                  "--add", "Microsoft.VisualStudio.Component.VC.MFC.ARM",
                  "--add", "Microsoft.VisualStudio.Component.VC.MFC.ARM.Spectre",
                  "--add", "Microsoft.VisualStudio.Component.VC.MFC.ARM64",
                  "--add", "Microsoft.VisualStudio.Component.VC.MFC.ARM64.Spectre",
                  "--add", "Microsoft.VisualStudio.Component.VC.Modules.x86.x64",
                  "--add", "Microsoft.VisualStudio.Component.VC.Tools.ARM64EC",
                  "--add", "Microsoft.VisualStudio.Component.VC.Redist.MSM",
                  "--add", "Microsoft.VisualStudio.Component.VC.Runtimes.ARM.Spectre",
                  "--add", "Microsoft.VisualStudio.Component.VC.Runtimes.ARM64.Spectre",
                  "--add", "Microsoft.VisualStudio.Component.VC.Runtimes.x86.x64.Spectre",
                  "--add", "Microsoft.VisualStudio.Component.VC.TestAdapterForBoostTest",
                  "--add", "Microsoft.VisualStudio.Component.VC.TestAdapterForGoogleTest",
                  "--add", "Microsoft.VisualStudio.Component.VC.v141.x86.x64",
                  "--add", "Microsoft.VisualStudio.Component.VC.v141.x86.x64.Spectre",
                  "--add", "Microsoft.VisualStudio.Component.VC.v141.ARM.Spectre",
                  "--add", "Microsoft.VisualStudio.Component.VC.v141.ARM64.Spectre",
                  "--add", "Microsoft.VisualStudio.Component.VC.v141.ATL",
                  "--add", "Microsoft.VisualStudio.Component.VC.v141.ATL.ARM",
                  "--add", "Microsoft.VisualStudio.Component.VC.v141.ATL.ARM64",
                  "--add", "Microsoft.VisualStudio.Component.VC.v141.ATL.ARM.Spectre",
                  "--add", "Microsoft.VisualStudio.Component.VC.v141.ATL.ARM64.Spectre",
                  "--add", "Microsoft.VisualStudio.Component.VC.v141.ATL.Spectre",
                  "--add", "Microsoft.VisualStudio.Component.VC.v141.MFC",
                  "--add", "Microsoft.VisualStudio.Component.VC.v141.MFC.ARM.Spectre",
                  "--add", "Microsoft.VisualStudio.Component.VC.v141.MFC.ARM64.Spectre",
                  "--add", "Microsoft.VisualStudio.Component.VC.v141.MFC.Spectre",
                  "--add", "Microsoft.VisualStudio.Component.VC.14.25.x86.x64",
                  "--add", "Microsoft.VisualStudio.Component.Windows10SDK.19041",
                  "--add", "Microsoft.VisualStudio.Component.WinXP",
                  "--add", "Microsoft.VisualStudio.Component.Workflow",
                  "--add", "Microsoft.VisualStudio.ComponentGroup.Azure.CloudServices",
                  "--add", "Microsoft.VisualStudio.ComponentGroup.Azure.ResourceManager.Tools",
                  "--add", "Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Llvm.Clang",
                  "--add", "Microsoft.VisualStudio.ComponentGroup.Web.CloudTools",
                  "--add", "Microsoft.VisualStudio.ComponentGroup.UWP.VC",
                  "--add", "Microsoft.VisualStudio.ComponentGroup.UWP.VC.v141",
                  "--add", "Microsoft.VisualStudio.Workload.Azure",
                  "--add", "Microsoft.VisualStudio.Workload.Data",
                  "--add", "Microsoft.VisualStudio.Workload.DataScience",
                  "--add", "Microsoft.VisualStudio.Workload.ManagedDesktop",
                  "--add", "Microsoft.VisualStudio.Workload.ManagedGame",
                  "--add", "Microsoft.VisualStudio.Workload.NativeCrossPlat",
                  "--add", "Microsoft.VisualStudio.Workload.NativeDesktop",
                  "--add", "Microsoft.VisualStudio.Workload.NativeGame",
                  "--add", "Microsoft.VisualStudio.Workload.NativeMobile",
                  "--add", "Microsoft.VisualStudio.Workload.NetCoreTools",
                  "--add", "Microsoft.VisualStudio.Workload.NetCrossPlat",
                  "--add", "Microsoft.VisualStudio.Workload.NetWeb",
                  "--add", "Microsoft.VisualStudio.Workload.Node",
                  "--add", "Microsoft.VisualStudio.Workload.Office",
                  "--add", "Microsoft.VisualStudio.Workload.Python",
                  "--add", "Microsoft.VisualStudio.Workload.Universal",
                  "--add", "Microsoft.VisualStudio.Workload.VisualStudioExtension",
                  "--add", "Component.MDD.Linux",
                  "--add", "Component.MDD.Linux.GCC.arm"
                  "--allWorkloads", "--includeRecommended", "--remove Component.CPython3.x64",
                  "--passive", "--norestart"
              ) -Wait -PassThru 

              Write-Output "VS2019安装程序退出代码: $($process.ExitCode)"

              Get-ChildItem -Path "C:\Program Files\Microsoft Visual Studio\"
              Get-ChildItem -Path "C:\Program Files (x86)\Microsoft Visual Studio\"
              Get-ChildItem -Path "C:\"
              Get-ChildItem -Path "C:\VS2019\VC\Tools\MSVC\"

              Get-ChildItem -Path "C:\VS2019\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\"

              # if (-not (Test-Path "C:\VS2019\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe")) {
              #   throw "MSVC 142工具集安装失败，未找到编译器cl.exe"
              # }
              echo "VS2019及所需组件安装完成"
      - name: Set toolset v142
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: "x64"
          toolset: "14.2"